services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
      - zookeeper_secrets:/etc/zookeeper/secrets
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
      - kafka_secrets:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  redis:
    image: redis:7
    container_name: redis
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--appendfilename", "appendonly.aof",
        "--aof-use-rdb-preamble", "yes",
        "--save", "900", "1",
        "--save", "300", "10",
        "--save", "60", "10000",
        "--appendfsync", "everysec"
      ]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: cpo
      POSTGRES_USER: cpo
      POSTGRES_PASSWORD: cpo
    ports:
      - "12345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # Persist zookeeper data and transaction logs
  zookeeper_data:
    name: zookeeper_data
  zookeeper_log:
    name: zookeeper_log
  zookeeper_secrets:
    name: zookeeper_secrets
  # Persist kafka broker data
  kafka_data:
    name: kafka_data
  kafka_secrets:
    name: kafka_secrets
  # Redis data persistence
  redis_data:
    name: redis_data
  # PostgreSQL data persistence
  postgres_data:
    name: postgres_data
